#!/usr/bin/env python3
"""转换 EditThisCookie JSON 格式为 Netscape 格式"""
import json
import sys

def convert_json_to_netscape(json_file, netscape_file):
    with open(json_file, 'r', encoding='utf-8') as f:
        cookies = json.load(f)

    with open(netscape_file, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by cookie_converter.py\n\n")

        for cookie in cookies:
            domain = cookie.get('domain', '')
            host_only = cookie.get('hostOnly', False)
            include_subdomain = cookie.get('includeSubdomains', False)
            path = cookie.get('path', '/')
            secure = cookie.get('secure', False)
            expiration = cookie.get('expirationDate', 0)
            name = cookie.get('name', '')
            value = cookie.get('value', '')

            # Netscape 格式: domain, include_subdomain, path, secure, expiration, name, value
            include_subdomain_str = 'TRUE' if include_subdomain else 'FALSE'
            secure_str = 'TRUE' if secure else 'FALSE'
            expiration_str = str(int(expiration)) if expiration else '0'

            line = f"{domain}\t{include_subdomain_str}\t{path}\t{secure_str}\t{expiration_str}\t{name}\t{value}\n"
            f.write(line)

    print(f"转换完成！已保存到: {netscape_file}")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("用法: python cookie_converter.py <输入json文件> <输出netscape文件>")
        sys.exit(1)

    convert_json_to_netscape(sys.argv[1], sys.argv[2])