"""Cookie import, storage and lightweight validation."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Optional

from VideoDownloader.utils import data_path


class CookieManager:
    PLATFORMS = ("youtube", "bilibili", "douyin")

    def __init__(self, cookie_dir: str = "cookies"):
        self.cookie_dir = data_path(cookie_dir)
        self.cookie_dir.mkdir(parents=True, exist_ok=True)

    def get_cookie_path(self, platform: str) -> Path:
        self._validate_platform(platform)
        return self.cookie_dir / f"{platform}_cookies.txt"

    def save_cookie(self, platform: str, content: str) -> bool:
        self._validate_platform(platform)
        value = (content or "").strip()
        if not value:
            return False
        try:
            self.get_cookie_path(platform).write_text(value + "\n", encoding="utf-8")
            return True
        except OSError:
            return False

    def load_cookie(self, platform: str) -> Optional[str]:
        path = self.get_cookie_path(platform)
        if not path.exists():
            return None
        try:
            return path.read_text(encoding="utf-8").strip()
        except OSError:
            return None

    def get_cookie_path_for_yt_dlp(self, platform: str) -> Optional[str]:
        try:
            path = self.get_cookie_path(platform)
        except ValueError:
            return None
        return str(path.resolve()) if self.is_cookie_valid(platform) else None

    def is_cookie_valid(self, platform: str) -> bool:
        content = self.load_cookie(platform)
        if not content:
            return False
        lines = [
            line for line in content.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]
        return content.lstrip().startswith("# Netscape") and any(
            len(line.split("\t")) >= 7 for line in lines
        )

    def import_from_file(self, platform: str, file_path: str) -> bool:
        try:
            content = Path(file_path).read_text(encoding="utf-8-sig")
            if content.lstrip().startswith(("[", "{")):
                content = self._convert_json_to_netscape(content)
            return self.save_cookie(platform, content)
        except (OSError, ValueError, TypeError, json.JSONDecodeError):
            return False

    def import_from_text(self, platform: str, content: str) -> bool:
        try:
            value = content.strip()
            if value.startswith(("[", "{")):
                value = self._convert_json_to_netscape(value)
            return self.save_cookie(platform, value)
        except (ValueError, TypeError, json.JSONDecodeError):
            return False

    @staticmethod
    def _convert_json_to_netscape(json_content: str) -> str:
        data = json.loads(json_content)
        if isinstance(data, dict):
            data = data.get("cookies", [])
        if not isinstance(data, list):
            raise ValueError("Cookie JSON 必须是数组，或包含 cookies 数组")

        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by VideoDownloader",
        ]
        for cookie in data:
            if not isinstance(cookie, dict) or not cookie.get("name"):
                continue
            domain = str(cookie.get("domain") or "")
            host_only = bool(cookie.get("hostOnly", False))
            if not host_only and domain and not domain.startswith("."):
                domain = "." + domain
            expiration = cookie.get("expirationDate") or cookie.get("expiration") or 0
            try:
                expiration_value = str(int(float(expiration))) if expiration else "0"
            except (TypeError, ValueError):
                expiration_value = "0"
            lines.append(
                "\t".join(
                    [
                        domain,
                        "FALSE" if host_only else "TRUE",
                        str(cookie.get("path") or "/"),
                        "TRUE" if cookie.get("secure") else "FALSE",
                        expiration_value,
                        str(cookie.get("name") or ""),
                        str(cookie.get("value") or ""),
                    ]
                )
            )
        if len(lines) == 2:
            raise ValueError("Cookie JSON 中没有可用条目")
        return "\n".join(lines)

    def delete_cookie(self, platform: str) -> bool:
        path = self.get_cookie_path(platform)
        if not path.exists():
            return True
        try:
            path.unlink()
            return True
        except OSError:
            return False

    def get_all_cookies_status(self) -> Dict[str, Dict]:
        return {
            platform: {
                "path": str(self.get_cookie_path(platform)),
                "exists": self.get_cookie_path(platform).exists(),
                "valid": self.is_cookie_valid(platform),
            }
            for platform in self.PLATFORMS
        }

    @staticmethod
    def auto_detect_platform(url: str) -> Optional[str]:
        value = (url or "").lower()
        if "youtube.com" in value or "youtu.be" in value:
            return "youtube"
        if "bilibili.com" in value or "b23.tv" in value:
            return "bilibili"
        if "douyin.com" in value:
            return "douyin"
        return None

    @classmethod
    def _validate_platform(cls, platform: str) -> None:
        if platform not in cls.PLATFORMS:
            raise ValueError(f"不支持的平台: {platform}")
